source 'https://github.com/CocoaPods/Specs.git'

target 'Toilets in Bratislava' do
	platform :ios, '11.0'
	use_frameworks!
	pod 'GoogleMaps', '~>4.0.0'
	pod 'GooglePlaces', '~>4.0.0'
	pod 'Google-Maps-iOS-Utils', '~>3.1.4'
end
